apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-agent-resource-proxy-tls
spec:
  secretName: argocd-agent-resource-proxy-tls
  issuerRef:
    name: argocd-agent-ca
    kind: Issuer
  commonName: resource-proxy
  subject:
    organizationalUnits:
      - dynamic.redhatworkshops.io
  dnsNames:
  - argocd-agent-resource-proxy.gitops-control-plane.svc.cluster.local
